### ISSUE TITLE
Does not work with DJI controller

### ISSUE THREAD

**Issue by lukashaider** [taylorgoolsby/fpv-drone-issue-tracker#2]
Hey, I am not able to make it work with the DJI controller over USB. Is there any way to reconfigure it?

**Comment by taylorgoolsby** [comment]
Hi, can you confirm you have the channels setup correctly on your transmitter's settings?
I'm not familiar with the DJI controller. Is it possible to remap the channels? 
You need to set your channels like so:
CH1: Thr
CH2: Ail
CH3: Ele
CH4: Rud
CH5: Assign a potentiometer here to set a custom camera angle.
CH11: ARM SWITCH
CH12: This switch must be activated in order to use a custom camera angle on CH5. Angle is 30 if this is off.

___
If you have it setup correctly, can you try this: 

Are you on windows?

If you are can you try this:
1. Press the windows key, and type in "Bluetooth"  and choose the first option "Bluetooth and other device settings"
![bluetooth](https://user-images.githubusercontent.com/14286600/84711519-70d1d900-af1b-11ea-97da-8e3469e91686.jpg)

2. Click on the "Devices and printers" link on the right side of the window:
![image](https://user-images.githubusercontent.com/14286600/84711619-a24aa480-af1b-11ea-9a1a-0e5b11a090b1.png)

3. Does your controller appear on this screen? If it does, right-click it and choose "Game Controller Settings". In the new window choose "Properties". You should now see this:
![image](https://user-images.githubusercontent.com/14286600/84711826-08cfc280-af1c-11ea-959b-87bc79cb2e8b.png)

If you move your sticks around, you should see this screen respond.

Using this screen, can you tell me the binding of your controller?
For example, if you move the throttle axis on your controller, which axis on this screen moves?

**Comment by lukashaider** [comment]
Hey,

thank you very much for your long answer. I dont think it is possible to remap the DJI Controller.

Here is the configuration showed in a short video:
![dji_fpv_hid](https://user-images.githubusercontent.com/13654851/84840773-cd7ae400-b040-11ea-9e61-f117a7ca65be.gif)
![hidcontroller](https://user-images.githubusercontent.com/13654851/84840879-129f1600-b041-11ea-99ef-0d62a43fbd97.JPG)

**Comment by taylorgoolsby** [comment]
Wow thank you for that video. That's extremely helpful. 

Looks like you really need to be able to change the channel mapping in-game. I wasn't expecting people with DJI controller to not be able to remap, so I can increase the priority on in game settings. Maybe this weekend.

Sorry about that.

**Comment by lukashaider** [comment]
Hey, would be really great if its possible to remap it in-game. But that will take a lot of effort I guess.

Thanks for your work!
I'd be happy to test it out.

**Comment by taylorgoolsby** [comment]
I started on in-game remapping last night, and it's almost done! I'll report back when it's done!

**Comment by taylorgoolsby** [comment]
Ok in game settings is done now. You can bind your axis by clicking the channel button then moving the axis. Minecraft will detect will axis you moved and assign it to that channel.

Download 1.1.0: https://www.curseforge.com/minecraft/mc-mods/fpv-drone/files

**Comment by lukashaider** [comment]
Hey!

Thank you! Is it possible to allow the switch mapping to be between CH 6 and 32?

The DJI Controller just has 4 Switches from Channel 5 to 8. Therefore i cant arm the drone.

**Comment by taylorgoolsby** [comment]
Ah, I see. Looks like windows interprets DJI switches as axes instead of buttons.

I will fix it by allowing axis channels to be used as button channels.

**Comment by taylorgoolsby** [comment]
Should be fixed now on version 1.3.2.

**Comment by lukashaider** [comment]
Okay works great now!
